name = "Miro MVP Theme"
license = "MIT"
licenselink = "https://github.com/giograno/miro-mvp-theme/blob/master/LICENSE"
description = "A trivial hugo template for simple landing page and blogging"
homepage = "http://giograno.com/"
tags = []
features = []
min_version = "0.41.0"


[params]
    css = ["css/style.css"]

[author]
  name = "Giovanni Grano"
  homepage = "https://giograno.com"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 10

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 20
